# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_remind_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remind_sender_email',
            field=models.EmailField(default=b'', max_length=254),
        ),
    ]
