# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20161218_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remind_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='remind_sender_email',
            field=models.EmailField(default=b'hwtest0001@163.com', max_length=254),
        ),
    ]
