# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20161218_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='remind_only_onece',
            new_name='remind_only_once',
        ),
    ]
