# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20161218_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remind_sender_email',
            field=models.EmailField(default=b'taskmanager0001@163.com', max_length=254),
        ),
    ]
